In [1]:
# Array Manipulation

In [2]:
import numpy as np

In [3]:
arr=np.random.randint(1,10,(3,4))

In [4]:
arr

array([[7, 3, 8, 6],
       [1, 3, 2, 7],
       [5, 5, 8, 1]])

In [5]:
arr.reshape(2,6)

array([[7, 3, 8, 6, 1, 3],
       [2, 7, 5, 5, 8, 1]])

In [6]:
arr.reshape(2,-345)

array([[7, 3, 8, 6, 1, 3],
       [2, 7, 5, 5, 8, 1]])

In [7]:
arr.T

array([[7, 1, 5],
       [3, 3, 5],
       [8, 2, 8],
       [6, 7, 1]])

In [8]:
arr.flatten()

array([7, 3, 8, 6, 1, 3, 2, 7, 5, 5, 8, 1])

In [9]:
arr1=np.array([1,2,3,4,5])

In [10]:
arr1

array([1, 2, 3, 4, 5])

In [11]:
arr1.ndim

1

In [12]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [13]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4, 5]])

In [14]:
arr

array([[7, 3, 8, 6],
       [1, 3, 2, 7],
       [5, 5, 8, 1]])

In [15]:
np.squeeze(arr)

array([[7, 3, 8, 6],
       [1, 3, 2, 7],
       [5, 5, 8, 1]])

In [16]:
dta=np.array([[1],[2],[3]])

In [17]:
dta

array([[1],
       [2],
       [3]])

In [18]:
np.squeeze(dta)

array([1, 2, 3])

In [19]:
arr1

array([1, 2, 3, 4, 5])

In [20]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [23]:
np.roll(arr1,3)

array([3, 4, 5, 1, 2])

In [24]:
arr1

array([1, 2, 3, 4, 5])

In [25]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [26]:
#Binary Operation

In [27]:
arr1=np.random.randint(1,10,(3,4))

In [28]:
arr2=np.random.randint(1,10,(3,4))

In [29]:
arr1

array([[8, 6, 5, 5],
       [5, 9, 6, 7],
       [5, 1, 7, 1]])

In [30]:
arr2

array([[3, 8, 3, 5],
       [3, 9, 3, 5],
       [9, 4, 7, 4]])

In [31]:
arr1+arr2

array([[11, 14,  8, 10],
       [ 8, 18,  9, 12],
       [14,  5, 14,  5]])

In [32]:
arr1/arr2

array([[2.66666667, 0.75      , 1.66666667, 1.        ],
       [1.66666667, 1.        , 2.        , 1.4       ],
       [0.55555556, 0.25      , 1.        , 0.25      ]])

In [33]:
arr1%arr2

array([[2, 6, 2, 0],
       [2, 0, 0, 2],
       [5, 1, 0, 1]], dtype=int32)

In [34]:
arr1-arr2

array([[ 5, -2,  2,  0],
       [ 2,  0,  3,  2],
       [-4, -3,  0, -3]])

In [35]:
arr1**arr2

array([[      512,   1679616,       125,      3125],
       [      125, 387420489,       216,     16807],
       [  1953125,         1,    823543,         1]], dtype=int32)

In [36]:
arr1&arr2

array([[0, 0, 1, 5],
       [1, 9, 2, 5],
       [1, 0, 7, 0]], dtype=int32)

In [37]:
arr1

array([[8, 6, 5, 5],
       [5, 9, 6, 7],
       [5, 1, 7, 1]])

In [38]:
arr2

array([[3, 8, 3, 5],
       [3, 9, 3, 5],
       [9, 4, 7, 4]])

In [39]:
~arr1

array([[ -9,  -7,  -6,  -6],
       [ -6, -10,  -7,  -8],
       [ -6,  -2,  -8,  -2]], dtype=int32)

In [40]:
arr1|arr2

array([[11, 14,  7,  5],
       [ 7,  9,  7,  7],
       [13,  5,  7,  5]], dtype=int32)

In [41]:
arr1>arr2

array([[ True, False,  True, False],
       [ True, False,  True,  True],
       [False, False, False, False]])

In [42]:
# String function

In [43]:
arr=np.array(["amit","kumar"])

In [44]:
np.char.upper(arr)

array(['AMIT', 'KUMAR'], dtype='<U5')

In [45]:
np.char.title(arr)

array(['Amit', 'Kumar'], dtype='<U5')

In [46]:
np.char.capitalize(arr)

array(['Amit', 'Kumar'], dtype='<U5')

In [47]:
# Mathematical function

In [48]:
arr1

array([[8, 6, 5, 5],
       [5, 9, 6, 7],
       [5, 1, 7, 1]])

In [49]:
np.sin(arr1)

array([[ 0.98935825, -0.2794155 , -0.95892427, -0.95892427],
       [-0.95892427,  0.41211849, -0.2794155 ,  0.6569866 ],
       [-0.95892427,  0.84147098,  0.6569866 ,  0.84147098]])

In [50]:
np.cos(arr1)

array([[-0.14550003,  0.96017029,  0.28366219,  0.28366219],
       [ 0.28366219, -0.91113026,  0.96017029,  0.75390225],
       [ 0.28366219,  0.54030231,  0.75390225,  0.54030231]])

In [51]:
np.tan(arr1)

array([[-6.79971146, -0.29100619, -3.38051501, -3.38051501],
       [-3.38051501, -0.45231566, -0.29100619,  0.87144798],
       [-3.38051501,  1.55740772,  0.87144798,  1.55740772]])

In [52]:
np.tanh(arr1)

array([[0.99999977, 0.99998771, 0.9999092 , 0.9999092 ],
       [0.9999092 , 0.99999997, 0.99998771, 0.99999834],
       [0.9999092 , 0.76159416, 0.99999834, 0.76159416]])

In [53]:
np.log10(arr1)

array([[0.90308999, 0.77815125, 0.69897   , 0.69897   ],
       [0.69897   , 0.95424251, 0.77815125, 0.84509804],
       [0.69897   , 0.        , 0.84509804, 0.        ]])

In [54]:
np.exp(arr1)

array([[2.98095799e+03, 4.03428793e+02, 1.48413159e+02, 1.48413159e+02],
       [1.48413159e+02, 8.10308393e+03, 4.03428793e+02, 1.09663316e+03],
       [1.48413159e+02, 2.71828183e+00, 1.09663316e+03, 2.71828183e+00]])

In [55]:
np.sqrt(arr1)

array([[2.82842712, 2.44948974, 2.23606798, 2.23606798],
       [2.23606798, 3.        , 2.44948974, 2.64575131],
       [2.23606798, 1.        , 2.64575131, 1.        ]])

In [56]:
np.power(arr1,2)

array([[64, 36, 25, 25],
       [25, 81, 36, 49],
       [25,  1, 49,  1]], dtype=int32)

In [57]:
np.mean(arr1)

5.416666666666667

In [59]:
np.min(arr1)

1

In [60]:
np.max(arr1)

9

In [61]:
np.var(arr1)

5.409722222222221

In [62]:
np.std(arr1)

2.32588095615881