In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [4]:
ar=np.array(l)

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [8]:
a=[2,3,4]

In [9]:
np.asanyarray(a)

array([2, 3, 4])

In [10]:
b=np.matrix(l)

In [11]:
b

matrix([[1, 2, 3, 4, 5]])

In [12]:
np.asanyarray(b)

matrix([[1, 2, 3, 4, 5]])

In [13]:
a=np.array(l)

In [14]:
c=a

In [15]:
c

array([1, 2, 3, 4, 5])

In [16]:
a

array([1, 2, 3, 4, 5])

In [17]:
c[0]

1

In [18]:
c[0]=100 # shallow copy

In [19]:
c

array([100,   2,   3,   4,   5])

In [20]:
a

array([100,   2,   3,   4,   5])

In [21]:
d=np.copy(a) #deep copy

In [22]:
d

array([100,   2,   3,   4,   5])

In [23]:
a

array([100,   2,   3,   4,   5])

In [24]:
a[1]=400

In [25]:
d

array([100,   2,   3,   4,   5])

In [26]:
a

array([100, 400,   3,   4,   5])

In [27]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [31]:
iterable=(i*i for i in range(5))

In [32]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [33]:
np.fromstring('234 234',sep=' ')

array([234., 234.])

In [34]:
np.fromstring('4,5',sep=",")

array([4., 5.])

In [35]:
l=[2,3,4,5,6]

In [36]:
ar=np.array(l)

In [37]:
ar

array([2, 3, 4, 5, 6])

In [39]:
ar.ndim

1

In [40]:
ar2=np.array([[1,2,3,4],[5,6,7,8]])

In [41]:
ar2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
ar2.ndim

2

In [43]:
ar.shape

(5,)

In [44]:
ar2.shape

(2, 4)

In [47]:
ar2.dtype

dtype('int32')

In [49]:
ar22=np.array([(1.4,45,45),(23,45,56)])

In [50]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 56. ]])

In [51]:
ar22.dtype

dtype('float64')

In [52]:
range(5)

range(0, 5)

In [53]:
list(range(5))

[0, 1, 2, 3, 4]

In [54]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [56]:
list(np.arange(2.3,5.6,0.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [57]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [58]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [59]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [61]:
np.ones(4)

array([1., 1., 1., 1.])

In [62]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [64]:
on=np.ones((2,3,4))

In [65]:
on+5

array([[[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]],

       [[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]])

In [66]:
on+4

array([[[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]]])

In [68]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [70]:
np.linspace(2,3,20)

array([2.        , 2.05263158, 2.10526316, 2.15789474, 2.21052632,
       2.26315789, 2.31578947, 2.36842105, 2.42105263, 2.47368421,
       2.52631579, 2.57894737, 2.63157895, 2.68421053, 2.73684211,
       2.78947368, 2.84210526, 2.89473684, 2.94736842, 3.        ])

In [71]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [72]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [74]:
arr=np.random.randn(3,4)

In [75]:
import pandas as pd

In [76]:
pd.DataFrame(arr)

0         1         2         3
0  1.491137  0.154101 -0.025257  0.144945
1  0.689603  0.998424 -1.881641  0.409590
2  0.645769  0.551768  1.357859  0.241913

In [77]:
np.random.rand(3,4)

array([[0.23313048, 0.83113345, 0.86603471, 0.47068441],
       [0.02854198, 0.5046052 , 0.13846043, 0.40475457],
       [0.23819065, 0.91656447, 0.96115788, 0.18470493]])

In [78]:
np.random.randint(1,110,(3,4))

array([[56, 99, 98, 54],
       [16, 80, 52, 95],
       [24, 97, 69, 82]])

In [79]:
arr

array([[ 1.49113744,  0.15410098, -0.02525727,  0.14494545],
       [ 0.68960291,  0.99842351, -1.88164092,  0.40959049],
       [ 0.64576901,  0.55176768,  1.35785924,  0.24191338]])

In [80]:
arr.reshape(6,2)

array([[ 1.49113744,  0.15410098],
       [-0.02525727,  0.14494545],
       [ 0.68960291,  0.99842351],
       [-1.88164092,  0.40959049],
       [ 0.64576901,  0.55176768],
       [ 1.35785924,  0.24191338]])

In [81]:
data=pd.DataFrame(np.random.randint(1,110,(300,4400))).to_csv('teest.csv')

In [82]:
data=pd.DataFrame(np.random.randint(1,110,(300,4400)))

In [83]:
data

0     1     2     3     4     5     6     7     8     9     ...  4390  \
0      26    51    75    49    66   105    85    95    41    93  ...    49   
1     104    21    76    71    96    28    54     7   103    57  ...   109   
2      66    22    92   100    38     8    14     3     8    85  ...    95   
3      78    87    32    23    37    23    70    37    18    34  ...    77   
4      45    94   108    16    30    66    49    76    23    80  ...    53   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
295    33    34    78    11    31   108     1    58    95     7  ...    19   
296    52    22    93    13    28    14    69    76    22   107  ...    19   
297    18    48    88    41    16    78    93     7    69    58  ...    36   
298   106    41    63    76    72    61    49    13    86    75  ...     2   
299    77    32    41    97     6    20    51    75    63     8  ...    25   

     4391  4392  4393  4394  4395  4396  4397  4398  4399  
0      84    86    14    76    20    38    73     6    53  
1      22    37    61    10    46    94    25    39    23  
2      68    35     2     4    82    72    93    83    90  
3      78    23    51    47    22    69    51    46   101  
4      61    46    13    78    95    91    11    64    50  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...  
295    69    53    39    68    97    56    43    81    51  
296    30    26    10   106    15    18     9    64    90  
297    75   103   107    62    10    27    59    86    53  
298    85    39    62    65    74    60    80    32    81  
299   104    30    94    87    71    51    57    24    31  

[300 rows x 4400 columns]

In [84]:
arr

array([[ 1.49113744,  0.15410098, -0.02525727,  0.14494545],
       [ 0.68960291,  0.99842351, -1.88164092,  0.40959049],
       [ 0.64576901,  0.55176768,  1.35785924,  0.24191338]])

In [86]:
arr1=arr.reshape(6,2)

In [87]:
arr1

array([[ 1.49113744,  0.15410098],
       [-0.02525727,  0.14494545],
       [ 0.68960291,  0.99842351],
       [-1.88164092,  0.40959049],
       [ 0.64576901,  0.55176768],
       [ 1.35785924,  0.24191338]])

In [92]:
arr1[1][1]

0.1449454478847904

In [93]:
arr1[2:5,1]

array([0.99842351, 0.40959049, 0.55176768])

In [95]:
d=np.random.randint(1,100,(5,5))

In [96]:
d

array([[76, 22, 62,  7, 69],
       [ 6,  9, 88, 80, 27],
       [24, 49, 85, 66, 28],
       [38, 35, 49, 65, 41],
       [ 2, 64, 82, 68, 13]])

In [98]:
d[d>50]

array([76, 62, 69, 88, 80, 85, 66, 65, 64, 82, 68])

In [99]:
d

array([[76, 22, 62,  7, 69],
       [ 6,  9, 88, 80, 27],
       [24, 49, 85, 66, 28],
       [38, 35, 49, 65, 41],
       [ 2, 64, 82, 68, 13]])

In [100]:
d[2:4,[1,2]]

array([[49, 85],
       [35, 49]])

In [101]:
d[0][0]=5000

In [102]:
d

array([[5000,   22,   62,    7,   69],
       [   6,    9,   88,   80,   27],
       [  24,   49,   85,   66,   28],
       [  38,   35,   49,   65,   41],
       [   2,   64,   82,   68,   13]])

In [104]:
d1=np.random.randint(1,3,(3,3))
d2=np.random.randint(1,3,(3,3))

In [105]:
d1

array([[1, 2, 2],
       [2, 2, 2],
       [1, 1, 1]])

In [106]:
d2

array([[1, 2, 2],
       [2, 1, 2],
       [1, 2, 1]])

In [107]:
d1+d2

array([[2, 4, 4],
       [4, 3, 4],
       [2, 3, 2]])

In [108]:
d1-d2

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, -1,  0]])

In [109]:
d1*d2

array([[1, 4, 4],
       [4, 2, 4],
       [1, 2, 1]])

In [110]:
d1@d2 #mutiplication using @

array([[ 7,  8,  8],
       [ 8, 10, 10],
       [ 4,  5,  5]])

In [111]:
d1/0

C:\Users\Amit Singh\AppData\Local\Temp\ipykernel_17852\4194278147.py:1: RuntimeWarning: divide by zero encountered in true_divide
  d1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [112]:
d1*100

array([[100, 200, 200],
       [200, 200, 200],
       [100, 100, 100]])

In [113]:
d1**2

array([[1, 4, 4],
       [4, 4, 4],
       [1, 1, 1]], dtype=int32)

In [114]:
#Broadcasting

In [115]:
arr=np.zeros((4,4))

In [116]:
row=np.array([1,2,3,4])

In [117]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [118]:
row.T

array([1, 2, 3, 4])

In [119]:
col=np.array([[1,2,3,4]])

In [121]:
col.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [122]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [123]:
arr1=np.random.randint(1,4,(3,4))

In [124]:
arr1

array([[1, 1, 3, 3],
       [3, 2, 3, 3],
       [3, 1, 3, 1]])

In [125]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.73205081, 1.73205081],
       [1.73205081, 1.41421356, 1.73205081, 1.73205081],
       [1.73205081, 1.        , 1.73205081, 1.        ]])

In [126]:
np.exp(arr1)

array([[ 2.71828183,  2.71828183, 20.08553692, 20.08553692],
       [20.08553692,  7.3890561 , 20.08553692, 20.08553692],
       [20.08553692,  2.71828183, 20.08553692,  2.71828183]])

In [127]:
np.log10(arr1)

array([[0.        , 0.        , 0.47712125, 0.47712125],
       [0.47712125, 0.30103   , 0.47712125, 0.47712125],
       [0.47712125, 0.        , 0.47712125, 0.        ]])