In [1]:
# Sort ,Search &Counting Function

In [2]:
import numpy as np

In [4]:
arr=np.array([4,3,4,5,6,7])

In [5]:
arr

array([4, 3, 4, 5, 6, 7])

In [6]:
np.sort(arr)

array([3, 4, 4, 5, 6, 7])

In [7]:
np.searchsorted(arr,34)

6

In [8]:
arr1=np.array([0,345,0,2,3,4,0,0,0])

In [9]:
np.count_nonzero(arr1)

4

In [11]:
np.where(arr1>6)

(array([1], dtype=int64),)

In [12]:
np.extract(arr>3,arr)

array([4, 4, 5, 6, 7])

In [13]:
arr.byteswap()

array([ 67108864,  50331648,  67108864,  83886080, 100663296, 117440512])

In [14]:
arr

array([4, 3, 4, 5, 6, 7])

In [15]:
a=np.copy(arr)

In [16]:
a

array([4, 3, 4, 5, 6, 7])

In [17]:
arr

array([4, 3, 4, 5, 6, 7])

In [18]:
b=arr.view() #shallow copy

In [19]:
b

array([4, 3, 4, 5, 6, 7])

In [20]:
b[0]=67

In [21]:
b

array([67,  3,  4,  5,  6,  7])

In [22]:
arr

array([67,  3,  4,  5,  6,  7])

In [23]:
# Matrix lib

In [25]:
import numpy.matlib as nm

In [26]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [27]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
nm.eye(9)

matrix([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [29]:
# Linear Algebra

In [30]:
arr1=np.random.randint([[2,3],[4,5]])
arr2=np.random.randint([[5,3],[2,5]])

In [31]:
np.dot(arr1,arr2)

array([[0, 0],
       [8, 2]])

In [32]:
arr1@arr2

array([[0, 0],
       [8, 2]])